### PR TITLE
Fix location filter parameters for streaming client

### LINKED ISSUE #169: Streaming: locations filter fix
This discussion follows PR #165 --- original discussion is [here](https://github.com/DanielaSfregola/twitter4s/pull/165#discussion_r146580205). I am gonna copy the relevant messages and continue the discussion here

### PR DESCRIPTION
**Pull request by allantl**
Fixes #169.

Refer to location model from [twitter-hbc](https://github.com/twitter/hbc/blob/master/hbc-core/src/main/java/com/twitter/hbc/core/endpoint/Location.java).

I find the name `Location` a bit ambiguous. So, I followed [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html) API, and name it `GeoBoundingBox`.

Also, from twitter docs, the documentation for locations are: A comma-separated list of longitude,latitude pairs specifying a set of bounding boxes to filter Tweets by.

### CODE REVIEW

File: src/main/scala/com/danielasfregola/twitter4s/entities/GeoCoordinate.scala [hunk 1]
```diff
@@ -0,0 +1,6 @@
+package com.danielasfregola.twitter4s.entities
+
+final case class GeoCoordinate(longitude: Double, latitude: Double) {
```
Comment (allantl) [inline src/main/scala/com/danielasfregola/twitter4s/entities/GeoCoordinate.scala]: We can also name this [GeoPosition](http://reference.wolfram.com/language/ref/GeoPosition.html) or [GeoLocation](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation).
I decided to follow [Microsoft](https://msdn.microsoft.com/en-us/library/system.device.location.geocoordinate(v=vs.110).aspx) and name it GeoCoordinate. 

One thing to note though, it seems that the standard order for coordinate is (latitude, longitude). But Twitter seems to follow (longitude, latitude) order. This might confuse some people.

Comment (DanielaSfregola) [reply src/main/scala/com/danielasfregola/twitter4s/entities/GeoCoordinate.scala]: I am very happy with the name you picked: I would stick with coordinate.

I wouldn't worry about people been confused: we are using a case class rather than a simple tuple exactly for that reason, so that can use named parameters.

File: src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala [hunk 2]
```diff
@@ -48,13 +49,13 @@ trait TwitterStatusClient {
     */
   def filterStatuses(follow: Seq[Long] = Seq.empty,
                      tracks: Seq[String] = Seq.empty,
-                     locations: Seq[Double] = Seq.empty,
+                     locations: GeoBoundingBoxes = GeoBoundingBoxes.empty,
```
Comment (DanielaSfregola) [inline src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala]: Why not simply have `Seq[GeoBoundingBox]` defaulted to Seq.empty? I think we do not actually need `GeoBoundingBoxes.empty` here...

File: src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBoxes.scala [hunk 3]
```diff
@@ -0,0 +1,11 @@
+package com.danielasfregola.twitter4s.entities
+
+final case class GeoBoundingBoxes(boundingBoxes: Seq[GeoBoundingBox]) {
```
Comment (DanielaSfregola) [inline src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBoxes.scala]: Not sure we actually need this case class...do we? At the end this is just `Seq[GeoBoundingBox]`...

File: src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBox.scala [hunk 4]
```diff
@@ -0,0 +1,6 @@
+package com.danielasfregola.twitter4s.entities
+
+final case class GeoBoundingBox(southwest: GeoCoordinate, northeast: GeoCoordinate) {
+  def toLngLatPairs: Seq[(Double, Double)] =
```
Comment (DanielaSfregola) [inline src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBox.scala]: I believe this could just be:
```
def toLngLatPairs: (Double, Double)
```
since the sequence would only contain only exactly 1 element

File: src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBoxes.scala (hunk 3 above)
Comment (DanielaSfregola) [reply src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBoxes.scala]: I actually think that this could be completely removed by using Seq[GeoBoundingBox] instead in the methods

**Comment by DanielaSfregola** [comment]
[Note to self] Careful, breaking change so do not merge before 5.2 is released

File: src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBox.scala (hunk 4 above)
Comment (allantl) [reply src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBox.scala]: The sequence would contain 2 elements since it has 2 coordinates, so its a 

    ((Double, Double),(Double, Double))

Comment (DanielaSfregola) [reply src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBox.scala]: Apologies, you are absolutely right! What you have done is the right thing 👍 

Please, ignore my comment

File: src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBoxes.scala (hunk 3 above)
Comment (allantl) [reply src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBoxes.scala]: I created this case class so that we don't need to do the conversion to query params, that is:

    boundingBoxes.flatMap(_.toLngLatPairs)

in each client method, e.g. in `TwitterStatusClient.filterStatuses`, I can just call `locations.toLngLatPairs`.

But, the bad thing is that we need to wrap it in another case class which looks redundant. What do you think?

Comment (DanielaSfregola) [reply src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBoxes.scala]: Having a case class just to have that method seems a bit too much to me too.
We could achieve the same by adding the function to the companion object for `GeoBoundingBox `. Something like the following:

```
object GeoBoundingBox {
    def toLngLatPairs(boundingBoxes: Seq[GeoBoundingBox]) = ???
}
```

and then ...

```
import GeoBoudingBox._
toLngLatPairs(boundingBoxes)
```

Comment (allantl) [reply src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBoxes.scala]: Yeah, I agree.

**Comment by allantl** [comment]
Ok, I did the improvements.

**Comment by DanielaSfregola** [comment]
5.2 is on its way to maven, merging
