### PR TITLE
Fix error when uploading media due to custom unmarshaller

### LINKED ISSUE #131: TwitterRestClient.uploadMediaFromPath and all its variants fail with cryptic message...
Simple Media upload of a "png" file fails with a cryptic message...

`[info] Running SlimClient 
Unexpected type info AnnotatedType(TypeRefType(NoPrefixType,TypeSymbol(T, owner=0, flags=12100, info=33 ),List()),List(40))
[success] Total time: 4 s, completed Aug 16, 2017 10:21:24 AM
`

The following program has been tried with 5.0, 5.1 and also SNAPSHOT-5.2 version of twitter4s.

```
import com.danielasfregola.twitter4s.TwitterRestClient
import scala.concurrent.Await
import scala.concurrent.ExecutionContext.Implicits.global
import scala.util.{Failure, Success}

object SlimClient extends App {

  // TODO - Make sure to define your consumer and access tokens!
  val client = TwitterRestClient()

  //client.createTweet(status = "Slim Client using twitter4s - Now with a change")
  val image = "/boxes/edcast/guideme/socialmedia/twitter/gmloader/data/tourvideo.png"
  val result = for {
    upload <- client.uploadMediaFromPath(image)
    tweet <- client.createTweet(status = "Test with media", media_ids = Seq(upload.media_id))
  } yield tweet

  result.onComplete {
    case Success(tweet) => println(tweet.id)
    case Failure(ex) => println(ex.getMessage)
  }

}
```

### PR DESCRIPTION
**Pull request by allantl**
Fix #131

Somehow [TwitterMediaClient.appendMediaChunk](https://github.com/DanielaSfregola/twitter4s/blob/a4a13a7649f8259a9510fa469fd6c5b9a2a64a4c/src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClient.scala#L119) is converted into `application/json` instead of `multipart/form-data` when post-ing due to custom unmarshaller related to the following akka-http [issue](https://github.com/akka/akka-http/issues/541) and akka-http-json [issue](https://github.com/hseeberger/akka-http-json/issues/148)

So, I just removed the implicit native serialization from `JsonSupport` and put it in scope where it is needed and it seems to work.

I would be glad if you had a better suggestion to solve the issue. Thanks!

### CODE REVIEW

File: src/main/scala/com/danielasfregola/twitter4s/http/serializers/JsonSupport.scala [hunk 1]
```diff
@@ -8,7 +8,7 @@ import org.json4s.{DefaultFormats, Formats, native}
 
 trait JsonSupport extends Json4sSupport {
 
-  implicit val serialization = native.Serialization
```
Comment (DanielaSfregola) [inline src/main/scala/com/danielasfregola/twitter4s/http/serializers/JsonSupport.scala]: Any particular reason why this has been changed?

**Comment by DanielaSfregola** [comment]
Hi @allantl, thanks for you contribution! 💃 

It's great and I think we are really close to merge it! See minor comment on removed implicit

File: src/main/scala/com/danielasfregola/twitter4s/http/serializers/JsonSupport.scala (hunk 1 above)
Comment (allantl) [reply src/main/scala/com/danielasfregola/twitter4s/http/serializers/JsonSupport.scala]: Due to this [bug](https://github.com/hseeberger/akka-http-json/issues/148), it unintendedly convert into `application/json` where it is not supposed to. The suggestion I got from that issue is to limit the scope of `JsonSupport` into the place where it is needed. But, that would lead to a bigger change.

Instead I limit the scope of serialization, since [Json4sSupport](https://github.com/hseeberger/akka-http-json/blob/master/akka-http-json4s/src/main/scala/de/heikoseeberger/akkahttpjson4s/Json4sSupport.scala) needs an implicit `Serialization`, so it will not unmarshall where its not needed. This leads to a smaller change and can be easily reverted.

I'll try to send a PR to revert this once the bug is fixed.

Comment (DanielaSfregola) [reply src/main/scala/com/danielasfregola/twitter4s/http/serializers/JsonSupport.scala]: Thanks for clarifying! It makes sense 👍

**Comment by DanielaSfregola** [comment]
LGTM
